### PR TITLE
Feature/unix sockets

### PR DESCRIPTION
**Pull request by boxofrox**
I rebased and preserved @mikezaby's commit from #1, added conditional macros to compile unix_sockets support on unix-based OS's, and included a unit test.

Also replaced `try!` macros per the rustfmt.toml.

Tested.

- ArchLinux
- neovim v0.2.0-827-g3f555cce3
- rust toolchain stable-x86_64-unknown-linux-gnu rustc 1.15.1 (021bd294c 2017-02-08)

### CODE REVIEW

**Comment by boxofrox** [comment]
Doh, neovim isn't installed in the TravisCI test environment and ubuntu precise doesn't have a neovim package in its repository.  I can `#[ignore]` the unit test, or do a bit of research to tweak the `travis.yml` to install neovim in the build environment.

**Comment by daa84** [comment]
Hello! thanks.
for me ignore is ok :)
also use std::path::Path; is used only in unix code, so maybe add cfg(unix) to it, to mute warning?

**Comment by boxofrox** [comment]
sounds good.  added `ignore` to test for now, and `cfg(unix)` to std::path::Path.

**Comment by mikezaby** [comment]
@boxofrox nice and sorry for that I left the previous PR incomplete.

**Comment by boxofrox** [comment]
...and I missed `use std::path::Path` in `test/lib.rs`.  Moved that inside the test and now it's `cfg(unix)`, too.

**Comment by daa84** [comment]
Thanks

**Pull request merged**
